apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "my-app-deployment"
  labels:
    app: "my-app"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "my-app-pod"
  template:
    metadata:
      labels:
        app: "my-app-pod"
    spec:
      containers:
      - name: "my-app-api"
        image: "husseinawala/my-app:latest"
        envFrom:
          - configMapRef:
              name: "my-app-config"
          - secretRef:
              name: "my-app-secret"
