apiVersion: "v1"
kind: "Secret"
metadata:
  name: "my-app-secret"
  labels:
    app: "my-app"
type: "Opaque"
data:
  USERNAME: ZmFzdGFwaQ==
  PASSWORD: ZmFzdGFwaQ==
  DB_HOST:  d3JpdGUgeW91ciBob3N0bmFtZSBoZXJl
  DB_NAME:  ZmFzdGFwaQ==
