apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-app.fullname" . }}
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
type: Opaque
data:
  USERNAME: {{ .Values.database.username | b64enc }}
  PASSWORD: {{ .Values.database.password | b64enc }}
  DB_HOST:  {{ .Values.database.hostname | b64enc }}
  DB_NAME:  {{ .Values.database.database | b64enc }}
